spring.application.name=OpenStackDemoServer

server.port=8090

# mybatis日志
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# 日志文件输出
logging.file.name=OpenStackDemoServer.log

# Openstack endpoint
openstack.endpoint=
# Openstack用户名
openstack.userId=
# Openstack密码
openstack.secret=
# Openstack项目名
openstack.projectName=
# Openstack域名
openstack.domainName=

